server:
  port: 8100
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth?useSSL=false
    username: praveenkamath
    password:
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never

cache:
  stopRequestExpiryInHours: 4
  redis:
    host: localhost
    port: 6379

rateLimiter:
  outbound:
    maxCount: 50
    ttlInHours: 24